"""initial schema

Baseline migration covering the nine tables and six query indexes defined in
``server.database``.  Generated by autogenerate against that metadata, so it is
equivalent to ``metadata.create_all()`` — ``tests/test_migrations.py`` asserts
the two paths stay in agreement.

Revision ID: 3573a583044a
Revises:
Create Date: 2026-08-08 22:42:48.264445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3573a583044a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_integrity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('trusted_hash', sa.Text(), nullable=False),
    sa.Column('registered_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('hostname', sa.Text(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('rule_name', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('raw_event_json', sa.Text(), nullable=False),
    sa.Column('acknowledged', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('idx_alerts_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_alerts_hostname', ['hostname'], unique=False)
        batch_op.create_index('idx_alerts_rule_name', ['rule_name'], unique=False)

    op.create_table('audit_chain',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recorded_at', sa.Text(), nullable=False),
    sa.Column('hostname', sa.Text(), nullable=False),
    sa.Column('prev_hash', sa.Text(), nullable=False),
    sa.Column('event_json', sa.Text(), nullable=False),
    sa.Column('record_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('record_hash')
    )
    op.create_table('device_baseline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.Text(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('first_seen', sa.Text(), nullable=False),
    sa.Column('last_seen', sa.Text(), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('received_at', sa.Text(), nullable=False),
    sa.Column('hostname', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('serial', sa.Text(), nullable=True),
    sa.Column('manufacturer', sa.Text(), nullable=True),
    sa.Column('product', sa.Text(), nullable=True),
    sa.Column('bus_path', sa.Text(), nullable=True),
    sa.Column('transfer_bytes', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('idx_events_device_id', ['device_id'], unique=False)
        batch_op.create_index('idx_events_hostname', ['hostname'], unique=False)
        batch_op.create_index('idx_events_received_at', ['received_at'], unique=False)

    op.create_table('host_timezone',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.Text(), nullable=False),
    sa.Column('utc_offset_hours', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_table('log_anchors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Text(), nullable=False),
    sa.Column('chain_head_hash', sa.Text(), nullable=False),
    sa.Column('anchored_at', sa.Text(), nullable=False),
    sa.Column('server_signature', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('window_start', sa.Text(), nullable=False),
    sa.Column('window_end', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_table('user_baseline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('hostname', sa.Text(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('first_seen', sa.Text(), nullable=False),
    sa.Column('last_seen', sa.Text(), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_baseline')
    op.drop_table('risk_scores')
    op.drop_table('log_anchors')
    op.drop_table('host_timezone')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('idx_events_received_at')
        batch_op.drop_index('idx_events_hostname')
        batch_op.drop_index('idx_events_device_id')

    op.drop_table('events')
    op.drop_table('device_baseline')
    op.drop_table('audit_chain')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('idx_alerts_rule_name')
        batch_op.drop_index('idx_alerts_hostname')
        batch_op.drop_index('idx_alerts_created_at')

    op.drop_table('alerts')
    op.drop_table('agent_integrity')
    # ### end Alembic commands ###
