"""initial_schema

Revision ID: b408e8d86a8e
Revises: 
Create Date: 2026-05-05 09:31:04.004187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b408e8d86a8e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_certs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('cert_pem', sa.Text(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_certs_agent_id'), 'agent_certs', ['agent_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('rule', sa.String(length=256), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('device_id', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_agent_id'), 'alerts', ['agent_id'], unique=False)
    op.create_table('allowlisted_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=256), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allowlisted_devices_agent_id'), 'allowlisted_devices', ['agent_id'], unique=False)
    op.create_table('anchors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('chain_head_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_signature', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anchors_agent_id'), 'anchors', ['agent_id'], unique=False)
    op.create_table('baseline_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=256), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seen_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_baseline_devices_agent_id'), 'baseline_devices', ['agent_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('actor', sa.String(length=256), nullable=False),
    sa.Column('device_id', sa.String(length=256), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_agent_id'), 'events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_events_device_id'), 'events', ['device_id'], unique=False)
    op.create_index(op.f('ix_events_event_id'), 'events', ['event_id'], unique=True)
    op.create_table('honeypot_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vid', sa.String(length=8), nullable=False),
    sa.Column('pid', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trusted_binary_hashes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('hash_value', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trusted_binary_hashes_agent_id'), 'trusted_binary_hashes', ['agent_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trusted_binary_hashes_agent_id'), table_name='trusted_binary_hashes')
    op.drop_table('trusted_binary_hashes')
    op.drop_table('honeypot_profiles')
    op.drop_index(op.f('ix_events_event_id'), table_name='events')
    op.drop_index(op.f('ix_events_device_id'), table_name='events')
    op.drop_index(op.f('ix_events_agent_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_baseline_devices_agent_id'), table_name='baseline_devices')
    op.drop_table('baseline_devices')
    op.drop_index(op.f('ix_anchors_agent_id'), table_name='anchors')
    op.drop_table('anchors')
    op.drop_index(op.f('ix_allowlisted_devices_agent_id'), table_name='allowlisted_devices')
    op.drop_table('allowlisted_devices')
    op.drop_index(op.f('ix_alerts_agent_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_agent_certs_agent_id'), table_name='agent_certs')
    op.drop_table('agent_certs')
    # ### end Alembic commands ###
